import{ supabase }from'./supabase/client';
export async function getCandidateProfile(userId:string){const{data,error}=await supabase.from('candidate_profiles').select('*').eq('user_id',userId).single();if(error)throw error;return data;}
export async function updateCandidateProfile(userId:string,x:any){const{data,error}=await supabase.from('candidate_profiles').update(x).eq('user_id',userId).select().single();if(error)throw error;return data;}
export async function getPublicCandidates(){const{data,error}=await supabase.from('candidate_profiles').select('*,candidate_portfolio(*)').eq('visibility','public').order('updated_at',{ascending:false});if(error)throw error;return data??[];}
export async function getCandidateById(id:string){const{data,error}=await supabase.from('candidate_profiles').select('*,candidate_portfolio(*)').eq('id',id).single();if(error)throw error;return data;}
async function upload(userId:string,file:File,folder:string){const limit=file.type==='application/pdf'?10:5;if(file.size>limit*1024*1024)throw new Error(`Limite ${limit} MB.`);if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Formato non consentito.');const path=`${userId}/${folder}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const{error}=await supabase.storage.from('candidate-files').upload(path,file,{contentType:file.type});if(error)throw error;const{data}=await supabase.storage.from('candidate-files').createSignedUrl(path,86400);return{path,url:data?.signedUrl??path};}
export async function uploadCandidateCv(userId:string,file:File){if(file.type!=='application/pdf')throw new Error('Il CV deve essere PDF.');return upload(userId,file,'cv');}
export async function uploadCandidatePortfolio(userId:string,candidateId:string,file:File,description=''){const u=await upload(userId,file,'portfolio');const{data,error}=await supabase.from('candidate_portfolio').insert({candidate_id:candidateId,file_url:u.url,storage_path:u.path,file_type:file.type,description}).select().single();if(error)throw error;return data;}
export async function deleteCandidatePortfolioItem(item:any){if(item.storage_path)await supabase.storage.from('candidate-files').remove([item.storage_path]);const{error}=await supabase.from('candidate_portfolio').delete().eq('id',item.id);if(error)throw error;}
export async function saveCandidate(ownerId:string,candidateId:string){const{error}=await supabase.from('saved_candidates').insert({owner_id:ownerId,candidate_id:candidateId});if(error)throw error;}
export async function unsaveCandidate(ownerId:string,candidateId:string){const{error}=await supabase.from('saved_candidates').delete().eq('owner_id',ownerId).eq('candidate_id',candidateId);if(error)throw error;}
export async function getSavedCandidates(ownerId:string){const{data,error}=await supabase.from('saved_candidates').select('*,candidate_profiles(*)').eq('owner_id',ownerId);if(error)throw error;return data??[];}
