-- Expand the active service area catalogue around Salerno and Naples.
insert into public.italian_locations (city, province, region, active) values
  ('Acerno', 'Salerno', 'Campania', true),
  ('Agropoli', 'Salerno', 'Campania', true),
  ('Albanella', 'Salerno', 'Campania', true),
  ('Amalfi', 'Salerno', 'Campania', true),
  ('Atrani', 'Salerno', 'Campania', true),
  ('Bellizzi', 'Salerno', 'Campania', true),
  ('Bracigliano', 'Salerno', 'Campania', true),
  ('Buccino', 'Salerno', 'Campania', true),
  ('Castel San Giorgio', 'Salerno', 'Campania', true),
  ('Castelcivita', 'Salerno', 'Campania', true),
  ('Cetara', 'Salerno', 'Campania', true),
  ('Contursi Terme', 'Salerno', 'Campania', true),
  ('Giffoni Sei Casali', 'Salerno', 'Campania', true),
  ('Giffoni Valle Piana', 'Salerno', 'Campania', true),
  ('Maiori', 'Salerno', 'Campania', true),
  ('Minori', 'Salerno', 'Campania', true),
  ('Montecorvino Pugliano', 'Salerno', 'Campania', true),
  ('Montecorvino Rovella', 'Salerno', 'Campania', true),
  ('Olevano sul Tusciano', 'Salerno', 'Campania', true),
  ('Pellezzano', 'Salerno', 'Campania', true),
  ('Positano', 'Salerno', 'Campania', true),
  ('Praiano', 'Salerno', 'Campania', true),
  ('Ravello', 'Salerno', 'Campania', true),
  ('Roccapiemonte', 'Salerno', 'Campania', true),
  ('San Cipriano Picentino', 'Salerno', 'Campania', true),
  ('San Mango Piemonte', 'Salerno', 'Campania', true),
  ('San Valentino Torio', 'Salerno', 'Campania', true),
  ('Siano', 'Salerno', 'Campania', true),
  ('Tramonti', 'Salerno', 'Campania', true),
  ('Vietri sul Mare', 'Salerno', 'Campania', true),
  ('Boscoreale', 'Napoli', 'Campania', true),
  ('Boscotrecase', 'Napoli', 'Campania', true),
  ('Castellammare di Stabia', 'Napoli', 'Campania', true),
  ('Gragnano', 'Napoli', 'Campania', true),
  ('Lettere', 'Napoli', 'Campania', true),
  ('Massa Lubrense', 'Napoli', 'Campania', true),
  ('Meta', 'Napoli', 'Campania', true),
  ('Napoli', 'Napoli', 'Campania', true),
  ('Ottaviano', 'Napoli', 'Campania', true),
  ('Palma Campania', 'Napoli', 'Campania', true),
  ('Piano di Sorrento', 'Napoli', 'Campania', true),
  ('Poggiomarino', 'Napoli', 'Campania', true),
  ('Pompei', 'Napoli', 'Campania', true),
  ('San Giuseppe Vesuviano', 'Napoli', 'Campania', true),
  ('Sant''Antonio Abate', 'Napoli', 'Campania', true),
  ('Santa Maria la Carità', 'Napoli', 'Campania', true),
  ('Sorrento', 'Napoli', 'Campania', true),
  ('Terzigno', 'Napoli', 'Campania', true),
  ('Torre Annunziata', 'Napoli', 'Campania', true),
  ('Torre del Greco', 'Napoli', 'Campania', true),
  ('Vico Equense', 'Napoli', 'Campania', true)
on conflict (city, province) do update set
  region = excluded.region,
  active = excluded.active;
