import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CalendarClock, CheckCircle2, Edit3, Euro, MapPin, MessageCircle, Send, ShieldCheck, Star, UserCheck, XCircle } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { Avatar, Badge, Button, Card, Input, RatingStars, Select, Textarea } from '../components/UI';
import { useAuth } from '../lib/auth/useAuth';
import { getRequestById, updateServiceRequest } from '../lib/requests';
import type { RequestProposal, RequestStatus, RequestUrgency, ServiceRequest, ServiceReview } from '../lib/supabase/types';
import { getOrCreateRequestConversation } from '../lib/chat';
import { APP_ROUTES, buildAppRoute, navigateTo } from '../lib/navigation';
import { cancelServiceRequest, confirmRequestCompletion, confirmRequestStart, getRequestProposals, getServiceReview, selectRequestProfessional, submitRequestProposal, submitServiceReview, subscribeToRequestWorkflow, withdrawRequestProposal } from '../lib/request-workflow';

const urgencyLabels = { urgent:'Urgente', today:'Oggi', tomorrow:'Entro domani', week:'Questa settimana', not_urgent:'Non urgente' };
const statusLabels:Record<RequestStatus,string>={open:'Aperta',awaiting_client_choice:'In attesa della scelta',assigned:'Professionista scelto',in_progress:'Lavoro in corso',awaiting_completion:'In attesa di conferma',completed:'Completata',cancelled:'Annullata'};

export const RequestDetail:React.FC=()=>{
  const{id=''}=useParams();const navigate=useNavigate();const{user,profile}=useAuth();
  const[request,setRequest]=useState<ServiceRequest|null>(null);const[proposals,setProposals]=useState<RequestProposal[]>([]);const[review,setReview]=useState<ServiceReview|null>(null);
  const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[editing,setEditing]=useState(false);const[saving,setSaving]=useState(false);
  const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[budget,setBudget]=useState('');const[urgency,setUrgency]=useState<RequestUrgency>('week');
  const[proposalOpen,setProposalOpen]=useState(false);const[proposalMessage,setProposalMessage]=useState('');const[availability,setAvailability]=useState('');

  const load=useCallback(async()=>{try{setError('');const item=await getRequestById(id);setRequest(item);if(item){setTitle(item.title);setDescription(item.description);setBudget(item.budget?.toString()??'');setUrgency(item.urgency);const loaded=await getRequestProposals(id);setProposals(loaded);if(item.status==='completed'&&item.client_id===user?.id)setReview(await getServiceReview(id));}}catch(err:any){setError(err.message);}finally{setLoading(false);}},[id,user?.id]);
  useEffect(()=>{void load();return subscribeToRequestWorkflow(id,()=>void load());},[id,load]);
  const owner=Boolean(user&&request?.client_id===user.id);const assigned=Boolean(user&&request?.assigned_user_id===user.id);const provider=profile?.role==='professional'||profile?.role==='company';
  const myProposal=useMemo(()=>proposals.find(item=>item.professional_user_id===user?.id)??null,[proposals,user?.id]);
  const selectedProposal=useMemo(()=>proposals.find(item=>item.status==='selected')??null,[proposals]);

  const save=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{const numericBudget=budget===''?null:Number(budget);if(!title.trim()||!description.trim()||(numericBudget!==null&&!Number.isFinite(numericBudget)))throw new Error('Controlla i dati inseriti.');setRequest(await updateServiceRequest(id,{title,description,urgency,budget:numericBudget}));setEditing(false);}catch(err:any){setError(err.message);}finally{setSaving(false);}};
  const propose=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{await submitRequestProposal(id,proposalMessage,availability);setProposalOpen(false);setNotice('La tua disponibilità è stata inviata al cliente.');await load();}catch(err:any){setError(err.message);}finally{setSaving(false);}};
  const withdraw=async()=>{if(!window.confirm('Vuoi ritirare la tua proposta?'))return;try{await withdrawRequestProposal(id);setNotice('Proposta ritirata.');await load();}catch(err:any){setError(err.message);}};
  const choose=async(item:RequestProposal)=>{const name=providerName(item);if(!window.confirm(`Vuoi affidare questa richiesta a ${name}?\n\nPotrete concordare dettagli, orario, prezzo e posizione precisa tramite la chat privata.`))return;setSaving(true);try{const conversation=await selectRequestProfessional(id,item.professional_user_id);await load();navigateTo(navigate,buildAppRoute(`/chat/${conversation.id}`));}catch(err:any){setError(err.message);}finally{setSaving(false);}};
  const openChat=async()=>{try{const conversation=await getOrCreateRequestConversation(id);navigateTo(navigate,buildAppRoute(`/chat/${conversation.id}`));}catch(err:any){setError(err.message);}};
  const start=async()=>{try{setRequest(await confirmRequestStart(id));setNotice('Conferma di inizio registrata.');await load();}catch(err:any){setError(err.message);}};
  const complete=async()=>{if(!window.confirm('Confermi che il lavoro è terminato? La richiesta sarà completata solo dopo la conferma dell’altra parte.'))return;try{setRequest(await confirmRequestCompletion(id));setNotice('Conferma registrata.');await load();}catch(err:any){setError(err.message);}};
  const cancel=async()=>{if(!window.confirm('Vuoi annullare questa richiesta? Le proposte ancora aperte saranno chiuse.'))return;try{setRequest(await cancelServiceRequest(id));setNotice('Richiesta annullata.');await load();}catch(err:any){setError(err.message);}};

  if(loading)return <Loading/>;if(!request)return <Unavailable error={error} onBack={()=>navigateTo(navigate,APP_ROUTES.requests)}/>;
  const actionable=owner||assigned;const elapsed=formatElapsed(request.created_at);
  return <div className="min-h-screen bg-zinc-50/60 pb-28"><header className="sticky top-0 z-20 border-b border-zinc-100 bg-white/90 px-5 py-4 backdrop-blur-xl"><div className="mx-auto flex max-w-5xl items-center justify-between"><button onClick={()=>navigateTo(navigate,APP_ROUTES.requests)} className="rounded-full p-2 hover:bg-zinc-100"><ArrowLeft size={19}/></button>{owner&&request.status==='open'&&<Button size="sm" variant="outline" onClick={()=>setEditing(value=>!value)}><Edit3 size={14}/> Modifica</Button>}</div></header>
    <main className="mx-auto max-w-5xl space-y-5 p-5 md:p-8">{error&&<Notice kind="error" text={error}/>} {notice&&<Notice kind="success" text={notice}/>}<div className="flex flex-wrap items-center gap-2"><Badge variant={request.status==='open'?'success':request.status==='completed'?'success':request.status==='cancelled'?'gray':'info'}>{statusLabels[request.status]}</Badge><Badge variant={request.urgency==='urgent'?'warning':'gray'}>{urgencyLabels[request.urgency]}</Badge><span className="ml-auto text-xs font-semibold text-zinc-400">Pubblicata {elapsed}</span></div>
      {editing?<Card hoverEffect={false}><form onSubmit={save} className="space-y-4"><Input label="Titolo" value={title} onChange={event=>setTitle(event.target.value)}/><Textarea label="Descrizione" value={description} onChange={event=>setDescription(event.target.value)} rows={6}/><div className="grid gap-4 sm:grid-cols-2"><Select label="Urgenza" value={urgency} onChange={event=>setUrgency(event.target.value as RequestUrgency)} options={Object.entries(urgencyLabels).map(([value,label])=>({value,label}))}/><Input label="Budget (€)" type="number" min="0" value={budget} onChange={event=>setBudget(event.target.value)}/></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setEditing(false)}>Annulla</Button><Button disabled={saving}>{saving?'Salvataggio…':'Salva modifiche'}</Button></div></form></Card>:<RequestSummary request={request}/>}
      {(request.request_media?.length??0)>0&&<Card hoverEffect={false}><h2 className="mb-4 text-sm font-black">Allegati</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-3">{request.request_media!.map(media=>media.file_type.startsWith('image/')?<img key={media.id} src={media.file_url} alt={media.file_name??'Allegato'} className="aspect-square w-full rounded-2xl object-cover"/>:<video key={media.id} src={media.file_url} controls className="aspect-square w-full rounded-2xl bg-black object-cover"/>)}</div></Card>}
      {provider&&['open','awaiting_client_choice'].includes(request.status)&&<ProviderProposal proposal={myProposal} open={proposalOpen} setOpen={setProposalOpen} message={proposalMessage} setMessage={setProposalMessage} availability={availability} setAvailability={setAvailability} saving={saving} onSubmit={propose} onWithdraw={withdraw}/>}
      {owner&&<ProposalList proposals={proposals} request={request} saving={saving} onChoose={choose} onProfile={()=>navigateTo(navigate,APP_ROUTES.professionals)}/>}
      {selectedProposal&&<Card hoverEffect={false} className="border-blue-100 bg-blue-50"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-black uppercase tracking-wider text-blue-600">Professionista scelto</p><h2 className="mt-1 text-lg font-black">{providerName(selectedProposal)}</h2><p className="mt-1 text-sm text-blue-800">Usate la chat privata per concordare prezzo, orario e dettagli.</p></div>{actionable&&<Button onClick={openChat}><MessageCircle size={16}/> Apri chat</Button>}</div></Card>}
      {actionable&&['assigned','in_progress'].includes(request.status)&&<WorkActions request={request} owner={owner} onStart={start} onComplete={complete}/>}
      {actionable&&request.status==='awaiting_completion'&&<CompletionState request={request} owner={owner} onComplete={complete}/>}
      {owner&&request.status==='completed'&&<ReviewForm requestId={id} existing={review} onSaved={saved=>{setReview(saved);setNotice('Grazie. La tua valutazione aiuterà altri utenti a scegliere il professionista più adatto.');}}/>}
      {owner&&['open','awaiting_client_choice','assigned'].includes(request.status)&&<Card hoverEffect={false} className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-black">Non hai più bisogno dell’intervento?</h2><p className="mt-1 text-xs text-zinc-500">Puoi annullare la richiesta; nessun professionista può chiuderla al posto tuo.</p></div><Button variant="danger" onClick={cancel}>Annulla richiesta</Button></Card>}
    </main></div>;
};

const RequestSummary=({request}:{request:ServiceRequest})=><Card hoverEffect={false} className="p-6 md:p-9"><span className="text-xs font-black uppercase tracking-widest text-blue-600">{request.categories?.name??'Servizio'}</span><h1 className="mt-2 text-2xl font-black md:text-4xl">{request.title}</h1><div className="mt-5 flex flex-wrap gap-x-6 gap-y-3 border-y border-zinc-100 py-4 text-sm font-semibold text-zinc-600"><span className="flex items-center gap-2"><MapPin size={17} className="text-blue-600"/> {request.city} ({request.province})</span><span className="flex items-center gap-2"><Euro size={17} className="text-blue-600"/> {request.budget==null?'Budget da concordare':`${request.budget} €`}</span><span className="flex items-center gap-2"><CalendarClock size={17} className="text-blue-600"/> {new Date(request.created_at).toLocaleString('it-IT')}</span></div><h2 className="mt-7 text-sm font-black">Descrizione dell’intervento</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-zinc-600">{request.description}</p><div className="mt-7 flex items-center gap-3 rounded-3xl bg-zinc-50 p-4"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-zinc-900 text-sm font-black text-white">CL</span><div><p className="text-sm font-bold">Cliente instaMax</p><p className="text-xs text-zinc-400">Identità e contatti protetti</p></div><ShieldCheck className="ml-auto text-emerald-500" size={20}/></div></Card>;

const ProviderProposal=({proposal,open,setOpen,message,setMessage,availability,setAvailability,saving,onSubmit,onWithdraw}:{proposal:RequestProposal|null;open:boolean;setOpen:(v:boolean)=>void;message:string;setMessage:(v:string)=>void;availability:string;setAvailability:(v:string)=>void;saving:boolean;onSubmit:(e:React.FormEvent)=>void;onWithdraw:()=>void})=><Card hoverEffect={false}>{proposal&&proposal.status!=='withdrawn'?<div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><Badge variant={proposal.status==='pending'?'warning':proposal.status==='selected'?'success':'gray'}>{proposal.status==='pending'?'Proposta inviata':proposal.status==='selected'?'Selezionato dal cliente':'Richiesta affidata a un altro professionista'}</Badge><p className="mt-3 text-sm text-zinc-500">{proposal.status==='pending'?'Il cliente può confrontare più disponibilità prima di scegliere.':'La proposta non è più modificabile.'}</p></div>{proposal.status==='pending'&&<Button variant="outline" onClick={onWithdraw}>Ritira proposta</Button>}</div>:open?<form onSubmit={onSubmit} className="space-y-4"><h2 className="text-lg font-black">Proponiti per il lavoro</h2><Textarea label="Messaggio di presentazione (facoltativo)" value={message} onChange={event=>setMessage(event.target.value)} maxLength={1000} rows={4}/><Input label="Disponibilità proposta" value={availability} onChange={event=>setAvailability(event.target.value)} maxLength={240} placeholder="Es. Domani dalle 15:00"/><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Annulla</Button><Button disabled={saving}><Send size={15}/> Invia disponibilità</Button></div></form>:<div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-black">Sei disponibile per questo lavoro?</h2><p className="mt-1 text-sm text-zinc-500">Invia la tua proposta: il cliente deciderà liberamente a chi affidare la richiesta.</p></div><Button onClick={()=>setOpen(true)}><UserCheck size={16}/> Proponiti per il lavoro</Button></div>}</Card>;

const ProposalList=({proposals,request,saving,onChoose,onProfile}:{proposals:RequestProposal[];request:ServiceRequest;saving:boolean;onChoose:(p:RequestProposal)=>void;onProfile:()=>void})=><Card hoverEffect={false}><div className="mb-5"><h2 className="text-lg font-black">Professionisti disponibili</h2><p className="mt-1 text-sm text-zinc-500">{proposals.filter(p=>p.status!=='withdrawn').length} disponibilità ricevute. Nessuno viene assegnato senza la tua conferma.</p></div><div className="space-y-4">{proposals.filter(p=>p.status!=='withdrawn').length?proposals.filter(p=>p.status!=='withdrawn').map(item=><div key={item.id} className="rounded-3xl border border-zinc-100 p-5"><div className="flex items-start gap-3"><Avatar name={providerName(item)} src={item.provider_profile?.avatar_url??undefined}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{providerName(item)}</h3>{providerVerified(item)&&<Badge variant="success">Verificato</Badge>}<Badge variant={item.status==='selected'?'success':item.status==='rejected'?'gray':'warning'}>{item.status==='pending'?'Disponibile':item.status==='selected'?'Selezionato':'Non selezionato'}</Badge></div><RatingStars rating={providerRating(item)} count={providerReviews(item)}/><p className="mt-2 text-sm font-bold">{providerPrice(item)}</p></div></div>{item.message&&<p className="mt-4 rounded-2xl bg-zinc-50 p-3 text-sm text-zinc-600">{item.message}</p>}{item.proposed_availability&&<p className="mt-3 text-sm"><b>Disponibilità:</b> {item.proposed_availability}</p>}<p className="mt-2 text-xs text-zinc-400"><MapPin size={12} className="mr-1 inline"/>Zona indicativa: {item.provider_profile?.city||request.city}</p><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={onProfile}>Visualizza profilo</Button>{item.status==='pending'&&request.status!=='assigned'&&<Button size="sm" disabled={saving} onClick={()=>onChoose(item)}>Scegli questo professionista</Button>}</div></div>):<p className="rounded-2xl bg-zinc-50 p-5 text-center text-sm text-zinc-500">Non sono ancora arrivate disponibilità.</p>}</div></Card>;

const WorkActions=({request,owner,onStart,onComplete}:{request:ServiceRequest;owner:boolean;onStart:()=>void;onComplete:()=>void})=>{const started=owner?request.client_start_confirmed:request.professional_start_confirmed;return <Card hoverEffect={false}><h2 className="text-lg font-black">Stato del lavoro</h2><p className="mt-2 text-sm text-zinc-500">{request.status==='in_progress'?'Il lavoro risulta in corso.':'Confermate l’inizio dopo aver concordato i dettagli in chat.'}</p><div className="mt-5 flex flex-wrap gap-2">{request.status==='assigned'&&!started&&<Button variant="outline" onClick={onStart}>Inizia lavoro</Button>}<Button onClick={onComplete}><CheckCircle2 size={16}/> Conferma lavoro terminato</Button></div></Card>;};
const CompletionState=({request,owner,onComplete}:{request:ServiceRequest;owner:boolean;onComplete:()=>void})=>{const mine=owner?request.client_completion_confirmed:request.professional_completion_confirmed;const other=owner?request.professional_completion_confirmed:request.client_completion_confirmed;return <Card hoverEffect={false} className="border-amber-100 bg-amber-50"><h2 className="font-black text-amber-950">Conferma conclusione</h2><p className="mt-2 text-sm text-amber-800">La tua conferma: <b>{mine?'ricevuta':'in attesa'}</b> · Altra parte: <b>{other?'ricevuta':'in attesa'}</b></p>{!mine&&<Button className="mt-4" onClick={onComplete}>Conferma lavoro terminato</Button>}</Card>;};

const ReviewForm=({requestId,existing,onSaved}:{requestId:string;existing:ServiceReview|null;onSaved:(r:ServiceReview)=>void})=>{const[rating,setRating]=useState(existing?.rating??0);const[comment,setComment]=useState(existing?.comment??'');const[aspects,setAspects]=useState({punctuality:existing?.punctuality??0,professionalism:existing?.professionalism??0,workQuality:existing?.work_quality??0,priceClarity:existing?.price_clarity??0,communication:existing?.communication??0});const[saving,setSaving]=useState(false);const[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(rating<1)return setError('Scegli una valutazione da 1 a 5 stelle.');setSaving(true);try{onSaved(await submitServiceReview(requestId,{rating,comment,...Object.fromEntries(Object.entries(aspects).map(([key,value])=>[key,value||null]))}));}catch(err:any){setError(err.message);}finally{setSaving(false);}};const options=[{value:'0',label:'Non specificato'},...([1,2,3,4,5].map(value=>({value:String(value),label:`${value} / 5`})))];return <Card hoverEffect={false}><h2 className="text-lg font-black">Valuta il lavoro ricevuto</h2><p className="mt-1 text-sm text-zinc-500">La recensione sarà collegata esclusivamente al professionista scelto.</p><form onSubmit={submit} className="mt-5 space-y-4">{error&&<Notice kind="error" text={error}/>}<div className="flex gap-2">{[1,2,3,4,5].map(value=><button type="button" key={value} onClick={()=>setRating(value)} aria-label={`${value} stelle`}><Star className={value<=rating?'fill-amber-400 text-amber-400':'text-zinc-300'} size={28}/></button>)}</div><div className="grid gap-3 sm:grid-cols-2"><Select label="Puntualità" value={String(aspects.punctuality)} onChange={event=>setAspects({...aspects,punctuality:Number(event.target.value)})} options={options}/><Select label="Professionalità" value={String(aspects.professionalism)} onChange={event=>setAspects({...aspects,professionalism:Number(event.target.value)})} options={options}/><Select label="Qualità del lavoro" value={String(aspects.workQuality)} onChange={event=>setAspects({...aspects,workQuality:Number(event.target.value)})} options={options}/><Select label="Chiarezza del prezzo" value={String(aspects.priceClarity)} onChange={event=>setAspects({...aspects,priceClarity:Number(event.target.value)})} options={options}/><Select label="Comunicazione" value={String(aspects.communication)} onChange={event=>setAspects({...aspects,communication:Number(event.target.value)})} options={options}/></div><Textarea label="Commento facoltativo" value={comment} onChange={event=>setComment(event.target.value)} maxLength={1500} rows={4}/><Button disabled={saving}>{saving?'Invio…':existing?'Aggiorna recensione':'Invia recensione'}</Button></form></Card>;};

const providerName=(p:RequestProposal)=>p.company_details?.company_name||p.professional_details?.business_name||p.provider_profile?.full_name||'Professionista instaMax';
const providerVerified=(p:RequestProposal)=>Boolean(p.company_details?.verified||p.professional_details?.verified);
const providerRating=(p:RequestProposal)=>Number(p.company_details?.rating??p.professional_details?.rating??0);
const providerReviews=(p:RequestProposal)=>Number(p.company_details?.total_reviews??p.professional_details?.total_reviews??0);
const providerPrice=(p:RequestProposal)=>{const d=p.company_details??p.professional_details;return d?.pricing_mode==='hourly'&&d.hourly_rate?`Da ${Number(d.hourly_rate).toLocaleString('it-IT',{minimumFractionDigits:2})} €/ora`:'Prezzo da concordare';};
const Notice=({kind,text}:{kind:'error'|'success';text:string})=><p className={`rounded-2xl border p-4 text-sm font-semibold ${kind==='error'?'border-red-100 bg-red-50 text-red-700':'border-emerald-100 bg-emerald-50 text-emerald-700'}`}>{text}</p>;
const Loading=()=> <div className="flex min-h-[70vh] items-center justify-center text-sm font-semibold text-zinc-400">Caricamento dettaglio…</div>;
const Unavailable=({error,onBack}:{error:string;onBack:()=>void})=><div className="flex min-h-[70vh] items-center justify-center p-6"><Card className="max-w-md text-center"><XCircle className="mx-auto text-red-500"/><h1 className="mt-3 text-lg font-black">Richiesta non disponibile</h1><p className="mt-2 text-sm text-zinc-500">{error||'Non esiste oppure non hai i permessi per visualizzarla.'}</p><Button className="mt-5" onClick={onBack}>Torna alle richieste</Button></Card></div>;
function formatElapsed(date:string){const seconds=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/1000));if(seconds<60)return'adesso';if(seconds<3600)return`${Math.floor(seconds/60)} minuti fa`;if(seconds<86400)return`${Math.floor(seconds/3600)} ore fa`;return`${Math.floor(seconds/86400)} giorni fa`;}
